### ISSUE TITLE
Your app is not working in new meteor 0.7.1

### ISSUE THREAD

**Issue by kwikiel** [chris-ramon/minitrello#3]
It only gives this error
=> Meteor server restarted
W20140121-22:16:47.665(1)? (STDERR) /Users/phoebe/Microscope/minitrello/.meteor/local/build/programs/server/boot.js:186
W20140121-22:16:47.668(1)? (STDERR) }).run();
W20140121-22:16:47.669(1)? (STDERR)    ^
W20140121-22:16:47.674(1)? (STDERR) ReferenceError: Meteor is not defined
W20140121-22:16:47.675(1)? (STDERR)     at app/minitrello.js:1:58
W20140121-22:16:47.676(1)? (STDERR)     at app/minitrello.js:145:3
W20140121-22:16:47.676(1)? (STDERR)     at /Users/phoebe/Microscope/minitrello/.meteor/local/build/programs/server/boot.js:155:10
W20140121-22:16:47.677(1)? (STDERR)     at Array.forEach (native)
W20140121-22:16:47.677(1)? (STDERR)     at Function._.each._.forEach (/Users/phoebe/.meteor/tools/09b63f1ed5/lib/node_modules/underscore/underscore.js:79:11)
W20140121-22:16:47.677(1)? (STDERR)     at /Users/phoebe/Microscope/minitrello/.meteor/local/build/programs/server/boot.js:82:5

**Comment by chris-ramon** [comment]
I've migrated minitrello to Meteor 1.1.0.2, documented the process [here](http://chrisramon.svbtle.com/migrate-0x-meteor-apps-to-1x)
